name: master
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  apply:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          terraform_wrapper: false

      - run: echo -n "$CREDENTIALS" > credentials.json
        env:
          CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - id: init
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json

      - id: validate
        run: terraform validate -no-color | tee validation

      - id: plan
        run: terraform plan -out=out.tfplan -no-color -input=false 2> plan_errors
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json

      - name: Apply
        run: terraform apply out.tfplan
        env:
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
